### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by aryuuuuuu** [furjac/FG_Torrents#1]
![image](https://github.com/furjac/FG_Torrents/assets/91587599/ad79a5f6-5e99-4d79-8b14-e987a56b5ee5)
check this out

**Comment by furjac** [comment]
use vpn and give n for the proxy at start

**Comment by furjac** [comment]
what  did  u chose in proxy
if y then u have to configure the premium proxy ok it will work

**Comment by aryuuuuuu** [comment]
> use vpn and give n for the proxy at start first issue

ig its working it says lemme cook something...

**Comment by furjac** [comment]
yea it will cook the internet 
lol thanks for using the software and make sure u use ublock origin(extension) on ur default browser

**Comment by furjac** [comment]
and ur a developer help me translation of this cli

**Comment by furjac** [comment]
@aryuuuuuu close the issue if resolved

**Comment by aryuuuuuu** [comment]
ok closing i m currently just a leaner and need to focus in studies so maybe later? btw nice knowing you
